Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -24,24 +24,27 @@ jobs:
 
       - name: Running Test Automation Framework with Maven
         run: |
-          mvn test -X -Dbrowser=chrome -DsikLambdaTest=true -DIsHeadless=false || echo "Tests failed, continuing to artifact upload"
+          mvn test site -X -Dbrowser=chrome -DsikLambdaTest=true -DIsHeadless=false || echo "Tests failed, continuing to artifact upload"
+
+      - name: Debug - List all files
+        run: ls -R
 
       - name: Upload Test logs
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: Test-logs
-          path: ./logs/**
+          path: target/surefire-reports/
 
       - name: Upload Test Reports
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: Test-report
-          path: ./report.html
+          path: target/site/
 
       - name: Test Execution Status
-        run: echo "Test Execution Completed"
+        run: echo "Test Execution Completed at $(date)"
 
 
 
